### python-CTD to convert 1 m binned CTD files (Seabird cnv) to a single csv for each station 

#### - Station 32/P2, April 2018 (Revelle, RR1804)

#### - Downloaded Al's 'ave' cnv files from the POMZ shared drive

    - Added 'ignore' to the DepthSM parameter in cnv because otherwise python-ctd wasn't sure which to use as index, pressure or depth.

In [19]:
import io
import requests
from pathlib import Path
import seaborn as sns
import pandas as pd

import ctd
import datetime

In [20]:
# read from cnv with 'ignore' added to depSM
cast57 = ctd.from_cnv("/home/millieginty/Documents/git-repos/2017-etnp/data/ctd-cnv/RR1804/Station32_cast57.cnv")

# split up and down casts; we want the downcast for the profile
down57, up57 = cast57.split()

# add a column with the start date and time in UTC (this is from the cnv header or from ship's log)
t = [datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ") for i in down57.index]
s = pd.Series(t, name = 'TimeStamp')
down57.insert(0, 'TimeStamp', s)

# look at downcast
down57.head()

,TimeStamp,timeS,scan,longitude,latitude,depSMignore,t090C,t190C,c0S/m,c1S/m,...,v7,sbeox0V,sal00,sal11,sigma-�00,sigma-�11,sbeox0Mg/L,sbox0Mm/Kg,sbeox0PS,flag
Pressure [dbar],,,,,,,,,,,,,,,,,,,,,
1.006,NaN,31.714,762.0,-106.97900,16.98438,1.0,26.8910,26.4595,5.392432,16.441289,...,0.0,2.6468,34.1915,237.4446,22.1436,224.7598,5.6145,171.657,85.200,False
2.012,NaN,41.104,987.0,-106.97898,16.98437,2.0,26.8769,26.9744,5.414921,3.079106,...,0.0,2.4906,34.3619,-10.5195,22.2765,-22.7610,6.0677,185.486,92.149,False
3.018,NaN,49.914,1199.0,-106.97897,16.98437,3.0,26.8888,26.8858,5.414856,5.429178,...,0.0,2.7794,34.3524,34.4565,22.2657,22.3450,6.5317,199.672,99.211,False
4.024,NaN,51.789,1244.0,-106.97896,16.98437,4.0,26.9041,26.9053,5.415320,5.435216,...,0.0,2.7390,34.3440,34.4851,22.2546,22.3604,6.4483,197.126,97.966,False
5.030,NaN,53.221,1278.0,-106.97896,16.98438,5.0,26.9042,26.9053,5.415237,5.431615,...,0.0,2.7404,34.3431,34.4592,22.2539,22.3410,6.4510,197.209,98.006,False

In [11]:
metadata57 = cast57._metadata

metadata57.keys()

dict_keys(['header', 'config', 'names', 'skiprows', 'time', 'lon', 'lat', 'name'])

### python-ctd saves the file metadata in a dictionary so that you have easy access later on.

### e.g., sensor serial #s and file creation metadata

In [12]:
print(metadata57["header"])

* Sea-Bird SBE 9 Data File:
* FileName = C:\CTD\RR1805\Station32_cast57.hex
* Software Version Seasave V 7.26.6.26
* Temperature SN = 4307
* Conductivity SN = 4650
* Number of Bytes Per Scan = 44
* Number of Voltage Words = 5
* Number of Scans Averaged by the Deck Unit = 1
* Append System Time to Every Scan
* System UpLoad Time = Apr 20 2018 11:01:56
* NMEA Latitude = 16 59.06 N
* NMEA Longitude = 106 58.74 W
* NMEA UTC (Time) = Apr 20 2018 11:01:51
* Store Lat/Lon Data = Append to Every Scan
** Ship: Revell
** Station: On Deck
** Operator: nak
* System UTC = Apr 20 2018 11:01:56
*END*

In [13]:
# Save the downcast to a csv

down57.to_csv("/home/millieginty/Documents/git-repos/2017-etnp/data/ctd-cnv/RR1804/Station32_cast57.csv")